proffer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

admin.site.site_header = "Proffer administration"
admin.site.site_title = "Proffer admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('',include('marketplace.urls')),
    path('accounts/',include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.urls import reverse

# Model ----Category-----
class Category(models.Model):
    category_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('products_by_category', args=[self.slug])


    def __str__(self):
        return self.category_name
    


# Model ----Subcategory-----
class Subcategory(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    subcategory_name = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Subcategory'
        verbose_name_plural = 'subcategories'

    def get_url(self):
        return reverse('products_by_subcategory', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.subcategory_name
        #return self.category.category_name + ' --> ' + self.subcategory_name

marketplace/models.py
from django.db import models
from category.models import Category, Subcategory
from accounts.models import Account, UserProfile
from ckeditor.fields import RichTextField

from django.db.models.signals import pre_save # Signals
# import the unique_slug_generator from .utils.py 
from .utils import unique_slug_generator

STATUS_PRODUCT=[
    ('Продавать','Продавать'),
    ('Покупать','Покупать'),
]

# Model ----Slider-----
class Slider(models.Model):
    DISCOUNT_CHOICES = (
        ('ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ','ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ'),
        ('НОВЫЕ ПОСТУПЛЕНИЯ','НОВЫЕ ПОСТУПЛЕНИЯ'),
        ('НОВЫЕ ПРЕДЛОЖЕНИЯ','НОВЫЕ ПРЕДЛОЖЕНИЯ'),
    )
    discount=models.CharField(max_length=100,choices=DISCOUNT_CHOICES,default='ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ')
    title = models.CharField(max_length=255,unique=True)
    intro = models.TextField(blank=True)
    image = models.ImageField(upload_to='media/slider')
    link = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Slider'
        verbose_name_plural = 'sliders'

    def __str__(self):
        return self.title

class Category_Banner(models.Model):
        name = models.CharField(max_length=255)
        slug = models.SlugField(unique=True, null=False)

        class Meta:
            verbose_name_plural = 'Category Banner'

        def __str__(self):
            return self.name

        def get_absolute_url(self):
            return self.slug

    
# Model ----banner_area-----
class Banner(models.Model):
    DRAFT = 'draft'
    ACTIVE = 'active'

    STATUS_BANNER = (
        (DRAFT, 'Draft'),
        (ACTIVE, 'Active'),
    )
    category = models.ForeignKey(Category_Banner, related_name="banners", on_delete=models.CASCADE)
    title = models.CharField(max_length=255,unique=True)
    intro = models.TextField(blank=True)
    image = models.ImageField(upload_to='media/banner')
    link = models.CharField(max_length=255, null=True, blank=True)
    status= models.CharField(max_length=50, choices=STATUS_BANNER, default=ACTIVE)

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

    def __str__(self):
        return self.title

# Model ----Section-----
class Section(models.Model):
    section_name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Section'
        verbose_name_plural = 'sections'

    def __str__(self):
        return self.section_name
    

# Model ----Product-----
class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    INACTIVE = 'Inactive'

    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    )

    DISTRICT_CHOICES=(
        ('Верх-Исетский район','Верх-Исетский район'),
        ('Железнодорожный район','Железнодорожный район'),
        ('Кировский район','Кировский район'),
        ('Ленинский район','Ленинский район'),
        ('Лесное кладбище','Лесное кладбище'),
        ('Октябрьский район','Октябрьский район'),
        ('Орджоникидзевский район','Орджоникидзевский район'),
        ('Чкаловский район','Чкаловский район'),
        ('микрорайон ЖБИ','микрорайон ЖБИ'),
        #('территория Юго-Восточный Район Изоплит','территория Юго-Восточный Район Изоплит'),
    )

    user = models.ForeignKey(Account, related_name='products', on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255, unique=True)
    status=models.CharField(max_length=15,choices=STATUS_PRODUCT, default='Продавать')
    status_for_product = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)
    price = models.IntegerField(null=True, blank=True)
    discount = models.IntegerField(null=True, blank=True)
    district = models.CharField(choices=DISTRICT_CHOICES, max_length=100, null=True, blank=True)
    address = models.CharField(max_length=255, unique=False, null=True, blank=True) 
    product_image = models.ImageField(upload_to='media/product', null=True, blank=True)
    #product_information = RichTextField(null=True, blank=True)
    #product_information = models.TextField(max_length=250, blank=True)
    model_name = models.CharField(max_length=255, null=True, blank=True)
    tags = models.CharField(max_length=255, null=True, blank=True)
    #description = RichTextField(blank=True)
    description = models.TextField(max_length=250, null=True, blank=True)
    #is_available = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    
    #Foreignkey
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, related_name='products', on_delete=models.CASCADE)
    section = models.ManyToManyField(Section, blank=True)
    #slug for link
    slug = models.SlugField(max_length=500, unique=True, blank=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'products'

    def clean(self):
        self.product_name = self.product_name.capitalize()

    def __str__(self):
        return self.product_name
    
    def get_absolute_url(self):
        from django.urls import reverse
        #return reverse("product_detail", kwargs={'slug': self.slug})
        return reverse('product_detail', args=[self.category.slug,self.subcategory.slug, self.slug])

def product_pre_save_receiver(sender, instance, *args, **kwargs):
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)
pre_save.connect(product_pre_save_receiver, sender=Product)
    

# Model ----Product_image-----
class Image_product(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/product', blank=True, null=True)

    def __str__(self):
        return self.product.product_name + "_image"


# Model ----Additional_information-----
class Additional_information(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.CharField(max_length=255, null=True, blank=True)
    detail = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.product.product_name + "_infosup"

# Model ----Wishlist-----
class Wishlist(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.product_name

proffer/views.py
from django.shortcuts import render
from marketplace.models import Slider,Banner, Category_Banner, Product

def home(request):
    all_sliders = Slider.objects.all().order_by('-id')[0:3]
    banners_bloc_1 = Banner.objects.filter(category__name="banner_bloc_1", status=Banner.ACTIVE).order_by('-id')[0:3]
    banners_bloc_2 = Banner.objects.filter(category__name="banner_bloc_2", status=Banner.ACTIVE).order_by('-id')[0:2]
    all_product = Product.objects.all()

    recommended_product = Product.objects.filter(section__section_name="Рекомендации", status_for_product=Product.ACTIVE)
    request_buy_product = Product.objects.filter(section__section_name="Заявки", status_for_product=Product.ACTIVE)
    product_and_service = Product.objects.filter(section__section_name="Товары_и_Услуги", status_for_product=Product.ACTIVE)
    



    context = {
        'all_sliders':all_sliders,
        'banners_bloc_1':banners_bloc_1,
        'banners_bloc_2':banners_bloc_2,
        'recommended_product':recommended_product,
        'request_buy_product':request_buy_product,
        'product_and_service':product_and_service,
        'all_product':all_product,

    }
    return render(request,'proffer/home.html',context)

templates/proffer/includes/header.html
{% load static %}
<!-- header-start -->
<!--<header class="header d-blue-bg fixed-top">-->
<header class="header d-blue-bg">
    <div class="header-top">
        <div class="container">
            <div class="header-inner">
                <div class="row align-items-center">
                    <div class="col-xl-5 col-lg-6">
                        <div class="header-inner-start">
                            <div class="header__currency border-right">
                                <div class="s-name">
                                    <span><i class="fa fa-location"></i></span>
                                </div>
                                <select>
                                    <option>Екатеринбург</option>
                                    <!--<option>Москва</option>-->
                                </select>
                            </div>
                            <div class="support d-none d-sm-block">
                                <p>Помощь ? <a href="#">+7 908 076 42 18</a></p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-xl-7 col-lg-6 d-none d-lg-block">
                        <div class="header-inner-end text-md-end">
                            <div class="ovic-menu-wrapper">
                                <ul>
                                    {% if user.id is None %}
                                    <li><a href="#">Работа в Proffer</a></li>
                                    <!--<li><a href="#"> Зарегистрироваться как продавец</a></li>-->
                                    <li><a href="#"> Продавайте на Proffer</a></li>
                                    <li><a href="{% url 'login' %}">Войти</a></li>
                                    <li><a href="{% url 'register' %}"> Зарегистрироваться</a></li>
                                    {% else %}
                                    <li><a href="#">Работа в Proffer</a></li>
                                    <li><a href="#"> Продавайте на Proffer</a></li>
                                    <li><a href="{% url 'logout' %}"> Выйти</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-mid">
        <div class="container">
            <div class="heade-mid-inner">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                        <div class="header__info">
                            <div class="logo">
                                <a href="{% url 'home' %}" class="logo-image"><img src="{% static 'assets/img/logo/logo-white.png' %}" alt="logo"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 d-none d-lg-block">
                        <div class="header__search">
                            <form action="{% url 'search' %}" method="GET">
                                <div class="header__search-box">
                                    <input class="search-input" type="text" placeholder="Что ищете?" name="keyword">
                                    <button class="button" type="submit"><i class="far fa-search"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-8 col-sm-8">
                        <div class="header-action">
                            <!--<div class="widget-header">
                                <small class="title text-muted">Welcome guest!</small>
                                <div> 
                                    <a href="#">Войти</a> <span class="dark-transp"> | </span>
                                    <a href="#">  Зарегистрироваться</a>
                                </div>
                            </div>-->
                            <div class="block-userlink">
                                <a class="icon-link" href="{% url 'dashboard' %}">
                                <i class="fa fa-user"></i>
                                <span class="text">
                                аккаунт </span>
                                </a>
                            </div>
                            <div class="block-wishlist action">
                                <a class="icon-link" href="{% url 'user_wishlist' %}">
                                <i class="fa fa-heart"></i>
                                <span id="wishlist_counter" class="count">{{ wishlist_count }}</span>
                                <span class="text">
                                избранное </span>
                                </a>
                            </div>

                            <div class="block-chat action">
                                <a class="icon-link" href="{% url 'user_message' %}">
                                <i class="fa fa-comment"></i>
                                <span class="count">0</span>
                                <span class="text">
                                сообщения </span>
                                </a>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header__bottom">
        <div class="container">
            <div class="row g-0 align-items-center">
                <div class="col-lg-3">                        
                    <div class="cat__menu-wrapper side-border d-none d-lg-block">
                        <div class="cat-toggle">
                            <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i>Каталоги</button>
                            <div class="cat__menu">
                                <nav id="mobile-menu" style="display: block;">
                                    <ul>
                                        <li><a href="{% url 'catalogue' %}">Посмотреть всё<i class="far fa-angle-down"></i></a></li>
                                        {% for category in links %}
                                        <li>
                                            <a href="#">{{category.category_name}} <i class="far fa-angle-down"></i></a>
                                            <ul class="submenu">
                                                <li><a href="{{category.get_url}}">Посмотреть всё</a></li>
                                                {% for cat in category.subcategory_set.all %}
                                                    <li><a href="{{cat.get_url}}">{{cat.subcategory_name}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        {% empty %}
                                        <li>
                                            <a href="#">Добавить категорию<i class="far fa-angle-down"></i></a>
                                            <ul class="submenu">
                                                <li><a href="#">Добавить подкатегорию</a></li>
                                            </ul>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-3">
                  <div class="header__bottom-left d-flex d-xl-block align-items-center">
                    <div class="side-menu d-lg-none mr-20">
                      <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-9">
                    <div class="shopeing-text text-sm-end">
                        <div class="slider-top-btn" data-animation="fadeInLeft" data-delay="1.5s">
                            <!--<a href="{% url 'add_product' %}" class="st-btn-b-add b-radius">Разместить объявление</a>-->
                            <a href="{% url 'add_product' %}" class="st-btn-b-add b-radius">Разместить объявление</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- header-end -->

templates/proffer/includes/modal.html
{% load static %}
{% load product_price_tags %}
     <!-- shop modal start -->
     {% for product in all_product %}
     <div class="modal fade" id="productModalId-{{product.id}}" tabindex="-1" role="dialog" aria-hidden="true">
         <div class="modal-dialog modal-dialog-centered product__modal" role="document">
             <div class="modal-content">
                 <div class="product__modal-wrapper p-relative">
                     <div class="product__modal-close p-absolute">
                         <button data-bs-dismiss="modal"><i class="fal fa-times"></i></button>
                     </div>
                     <div class="product__modal-inner">
                         <div class="row">
                         <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                             <div class="product__modal-box">
                                 <div class="tab-content" id="modalTabContent">

                                     <div class="tab-pane fade show active" id="nav{{image.id}}" role="tabpanel" aria-labelledby="nav{{image.id}}-tab">
                                         <div class="product__modal-img w-img">
                                             <img src="/media/{{product.image_product_set.first.image}}" alt="">
                                         </div>
                                     </div>

                                     {% for image in product.image_product_set.all %}
                                     <div class="tab-pane fade show" id="nav{{image.id}}" role="tabpanel" aria-labelledby="nav{{image.id}}-tab">
                                         <div class="product__modal-img w-img">
                                             <img src="/media/{{image.image}}" alt="">
                                         </div>
                                     </div>
                                     {% endfor %}
                                 </div>
                                 <ul class="nav nav-tabs" id="modalTab" role="tablist">
                                     {% for image in product.image_product_set.all %}
                                     <li class="nav-item" role="presentation">
                                         <button class="nav-link" id="nav{{image.id}}-tab" data-bs-toggle="tab" data-bs-target="#nav{{image.id}}" type="button" role="tab" aria-controls="nav{{image.id}}" aria-selected="true">
                                             <img src="/media/{{image.image}}" alt="" style="width: 85px; height: 85px;">
                                         </button>
                                     </li>
                                     {% endfor %}
                                 </ul>
                             </div>
                         </div>
                         <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                             <div class="product__modal-content">
                                 <h4><a href="#">{{product.product_name}}</a></h4>
                                    {% if product.discount %}
                                    <div class="product__price">
                                        <span>{% call_sellprice product.price product.discount %} ₽</span>&nbsp;<del>{{product.price}} ₽</del>
                                    </div>
                                    {% else %}
                                    <div class="price mb-10">
                                        <span>{{product.price}} ₽</span>
                                    </div>
                                    {% endif %}
                                 <div class="product__modal-des mt-20 mb-15">
                                     <ul>
                                         <li><a href="#">{{product.product_information|safe|truncatechars:600}}</a></li>                                    
                                     </ul>
                                     <ul>
                                        <li><a href="#">Екатеринбург, {{product.address}}</a></li>
                                     </ul>
                                     <ul>
                                        <li><a href="#">Вчера 09:34</a></li>
                                     </ul>
                                 </div>
                                 <!--<div class="product__stock mb-20">
                                     <span class="mr-10">Availability :</span>
                                     <span>1795 in stock</span>
                                 </div>-->
                                 <div class="product__modal-form">
                                     <!--<form action="#">-->
                                     <div class="pro-quan-area d-lg-flex align-items-center">
                                         <!--<div class="product-quantity mr-20 mb-25">
                                             <div class="cart-plus-minus p-relative"><input type="text" value="1" /></div>
                                         </div>-->
                                         {% if product.user != request.user %}
                                         <div class="pro-cart-btn mb-25">
                                             <button class="cart-btn">Написать</button>
                                         </div>
                                         {% endif %}
                                     </div>
                                     <!--</form>-->
                                 </div>
                                 <div class="product__stock mb-30">
                                     <ul>
                                         <li><a href="#">
                                             <span class="sku mr-10">Модель:</span>
                                             <span>{{product.model_name}}</span></a>
                                         </li>
                                         <li><a href="#">
                                             <span class="cat mr-10">Категория:</span>
                                             <span>{{product.category}}</span></a>
                                         </li>
                                         <li><a href="#">
                                             <span class="tag mr-10">Таги:</span>
                                             <span>{{product.tags}}</span></a>
                                         </li>
                                     </ul>
                                 </div>
                             </div>
                         </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     {% empty %}
     <!-- shop modal start -->
    <div class="modal fade" id="productModalId" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered product__modal" role="document">
            <div class="modal-content">
                <div class="product__modal-wrapper p-relative">
                    <div class="product__modal-close p-absolute">
                        <button data-bs-dismiss="modal"><i class="fal fa-times"></i></button>
                    </div>
                    <div class="product__modal-inner">
                        <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-box">
                                <div class="tab-content" id="modalTabContent">
                                    <div class="tab-pane fade show active" id="nav1" role="tabpanel" aria-labelledby="nav1-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{% static 'assets/img/quick-view/quick-view-1.jpg' %}" alt="">
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="nav2" role="tabpanel" aria-labelledby="nav2-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{% static 'assets/img/quick-view/quick-view-2.jpg' %}" alt="">
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="nav3" role="tabpanel" aria-labelledby="nav3-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{% static 'assets/img/quick-view/quick-view-3.jpg' %}" alt="">
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="nav4" role="tabpanel" aria-labelledby="nav4-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{% static 'assets/img/quick-view/quick-view-4.jpg' %}" alt="">
                                        </div>
                                    </div>
                                    </div>
                                <ul class="nav nav-tabs" id="modalTab" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link active" id="nav1-tab" data-bs-toggle="tab" data-bs-target="#nav1" type="button" role="tab" aria-controls="nav1" aria-selected="true">
                                            <img src="{% static 'assets/img/quick-view/quick-nav-1.jpg' %}" alt="">
                                        </button>
                                    </li>
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link" id="nav2-tab" data-bs-toggle="tab" data-bs-target="#nav2" type="button" role="tab" aria-controls="nav2" aria-selected="false">
                                        <img src="{% static 'assets/img/quick-view/quick-nav-2.jpg' %}" alt="">
                                        </button>
                                    </li>                                 
                                    </ul>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-content">
                                <h4><a href=" #">Добавить продукт</a></h4>
                                <div class="product__price">
                                    <span>Добавить цену</span>
                                </div>
                                <div class="product__modal-des mt-20 mb-15">
                                    <ul>
                                        <li><a href="#"><i class="fas fa-circle"></i>Добавить описание</a></li>
                                    </ul>
                                </div>
                                <div class="product__modal-form">
                                    <form action="#">
                                    <div class="pro-quan-area d-lg-flex align-items-center">
                                       <!-- <div class="product-quantity mr-20 mb-25">
                                            <div class="cart-plus-minus p-relative"><input type="text" value="1" /></div>
                                        </div>-->
                                        <div class="pro-cart-btn mb-25">
                                            <button class="cart-btn" type="submit">Написать</button>
                                        </div>
                                    </div>
                                    </form>
                                </div>
                                <div class="product__stock mb-30">
                                    <ul>
                                        <li><a href="#">
                                            <span class="sku mr-10">Модель: </span>
                                            <span>-</span></a>
                                        </li>
                                        <li><a href="#">
                                            <span class="cat mr-10">Категория:</span>
                                            <span>-</span></a>
                                        </li>
                                        <li><a href="#">
                                            <span class="tag mr-10">Тэги:</span>
                                            <span>-</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
     {% endfor %}
     <!-- shop modal end -->